-- admin user=pg

-- PLC
CREATE DATABASE plc;
GRANT ALL PRIVILEGES ON DATABASE plc TO pg;

-- BGS
CREATE DATABASE bgs;
GRANT ALL PRIVILEGES ON DATABASE bgs TO pg;
CREATE DATABASE carstore;
GRANT ALL PRIVILEGES ON DATABASE carstore TO pg;

-- bsky(AppView)
--CREATE DATABASE bsky;
--GRANT ALL PRIVILEGES ON DATABASE bsky TO pg;

-- search(palomar)
CREATE DATABASE search;
GRANT ALL PRIVILEGES ON DATABASE search TO pg;

-- pds
--CREATE DATABASE pds;
--GRANT ALL PRIVILEGES ON DATABASE pds TO pg;

-- ozone(Moderation)
CREATE DATABASE postgres;
GRANT ALL PRIVILEGES ON DATABASE postgres TO pg;
