-- PLC
CREATE DATABASE plc;
GRANT ALL PRIVILEGES ON DATABASE plc TO postgres;

-- BGS
CREATE DATABASE bgs;
GRANT ALL PRIVILEGES ON DATABASE bgs TO postgres;
CREATE DATABASE carstore;
GRANT ALL PRIVILEGES ON DATABASE carstore TO postgres;

-- bsky(AppView)
CREATE DATABASE bsky;
GRANT ALL PRIVILEGES ON DATABASE bsky TO postgres;

-- ozone(Moderation)
CREATE DATABASE mod;
GRANT ALL PRIVILEGES ON DATABASE mod TO postgres;

-- search(palomar)
CREATE DATABASE search;
GRANT ALL PRIVILEGES ON DATABASE search TO postgres;

-- PDS
-- CREATE DATABASE pds;
-- GRANT ALL PRIVILEGES ON DATABASE pds TO postgres;
